### PR TITLE
Pull prebuilt images from Dockerhub by default

### PR DESCRIPTION
**Pull request by JoshuaWatt**
Several improvements for pyrex, including
1. Pulling prebuilt images from dockerhub by default
2. Updating icecc to the latest version with many bug fixes
3. Using multistage builds in a unified Dockerfile
4. Using BuildKit for faster builds
5. Adding a Ubuntu 18.04 image
6. Removal of wine to reduce image size

### CODE REVIEW

**Comment by matthoosier-garmin** [comment]
Is there anything to be careful about with tagging and Travis CI hooks, when reviewing the merge of this into the main GitHub pyrex repo?

**Comment by matthoosier-garmin** [comment]
> Is there anything to be careful about with tagging and Travis CI hooks, when reviewing the merge of this into the main GitHub pyrex repo?

I'm thinking of the secret key you mentioned earlier.

**Comment by JoshuaWatt** [comment]
No, this should be all good to go (as is evidenced by the next branch populating the "next" tag on dockerhub).

**Comment by JoshuaWatt** [comment]
> No, this should be all good to go (as is evidenced by the next branch populating the "next" tag on dockerhub).

This Travis build pushed the "next" tag to dockerhub, proving the credentials are correct: https://travis-ci.org/garmin/pyrex/builds/547730651

**Comment by matthoosier-garmin** [comment]
Do we care about the failed check that's unhappy about a tiny reduction in the amount of code coverage?

**Comment by JoshuaWatt** [comment]
I don't think so. Coverage is more of a tool to verify we have good tests. I manually inspected the coverage changes and I don't think the changes are particularly bothersome.

Code coverage isn't a required check in GitHub for that reason

**Pull request merged**
