### PR TITLE
Podman support

### PR DESCRIPTION
**Pull request by JoshuaWatt**
Adds support for running Pyrex under podman in addition to Docker.

### CODE REVIEW

**Comment by JoshuaWatt** [comment]
> The 'docker save' -> 'podman load' stuff looks fine. Does that end up requiring that end users will need Docker unconditionally installed? Or is the runtime smart enough to only enforce /usr/bin/docker is present only when building an image?

It's controlled by any environment variable `USE_HELPER`. It's a little clunky right now, but I don't really know a better way to make it work, aside from upgrading to Ubuntu 19.10 which has full podman support, and presumably will work.

**Comment by matthoosier-garmin** [comment]
Yeah, I saw that part. I was just double-checking there's no expectation that day-to-day developers who just want to execute bitbake under podman, have to set USE_HELPER?

**Comment by JoshuaWatt** [comment]
> Yeah, I saw that part. I was just double-checking there's no expectation that day-to-day developers who just want to execute bitbake under podman, have to set USE_HELPER?

Day to day developers will not need to set `USE_HELPER` as long as they are pulling released images from dockerhub.

**Comment by kergoth** [comment]
Considered using https://github.com/genuinetools/img instead of `docker build` for building the image to load into podman? `img save user/myimage | podman load`.

**Comment by JoshuaWatt** [comment]
> Considered using https://github.com/genuinetools/img instead of `docker build` for building the image to load into podman? `img save user/myimage | podman load`.

Interesting. I might give that a try. The reasons for using Docker in this case are 3 fold:

1. The actual released images are built using docker, so testing the images built with docker in podman is the closest to reality
2. Docker builds the fastest (when BuildKit is enabled). We were having a lot of problems with timeouts on travis :(
3. It actually works.... building rootlessly in podman didn't work when fuse-overlayfs was used (which you want because otherwise it's *even slower*). I suspect this is because the fuse-overlayfs driver available in Ubuntu 18.04 (via PPA) is old because it works fine on my Fedora 31 desktop that has the newer fuse-overlayfs driver. Perhaps if/when travis gets support for Ubuntu 20.04 we can try again.

I actually discovered that podman can pull directly from the local docker registry:
```python
['podman', 'pull', 'docker-daemon:' + args.tag]
```
So I might try that instead

**Pull request merged**
